prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix obo: <http://purl.obolibrary.org/obo/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT ?commonIRI (count(?class) as ?class_count)
WHERE
{
    ?class a owl:Class .
    ?class oboInOwl:inSubset ?subset
    FILTER regex( str(?class), str(?commonIRI))
    FILTER regex( str(?subset), "FAIRsharing")

    { SELECT distinct (REPLACE( str(?class) , '_[^/]*$', '' ) AS ?commonIRI) WHERE { ?class a owl:Class } }

}
GROUP BY ?commonIRI
ORDER BY ASC(?commonIRI)
